added namespace

diff --git a/wait-for-deployment b/wait-for-deployment
--- a/wait-for-deployment
+++ b/wait-for-deployment
@@ -51,24 +51,26 @@ get_available_replicas() {
 get_deployment_jsonpath() {
   local -r jsonpath="$1"
 
-  kubectl get deployment "${deployment}" -o "jsonpath=${jsonpath}"
+  kubectl get deployment "${deployment}" -o "jsonpath=${jsonpath}" -n"${namespace}"
 }
 
 display_usage_and_exit() {
-  echo "Usage: $(basename "$0") <deployment> <[timeout]>" >&2
+  echo "Usage: $(basename "$0") <deployment> <namespace> <[timeout]>" >&2
   echo "Arguments:" >&2
   echo "deployment - REQUIRED: The name of the deployment the script should wait on" >&2
+  echo "namespace - REQUIRED: " >&2
   echo "timeout    - OPTIONAL: How long to wait for the deployment to be available, defaults to ${DEFAULT_TIMEOUT} seconds, must be greater than 0" >&2
   exit 1
 }
 
-if [ $# -lt 1 ] || [ $# -gt 2 ] ; then
+if [ $# -lt 1 ] || [ $# -gt 3 ] ; then
   display_usage_and_exit
 fi
 
 readonly deployment="$1"
+readonly namespace="$2"
 
-declare -xr timeout=${2:-$DEFAULT_TIMEOUT}
+declare -xr timeout=${3:-$DEFAULT_TIMEOUT}
 if [[ ${timeout} -le 0 ]]; then
   display_usage_and_exit
 fi
@@ -106,4 +108,4 @@ while [[ ${updated_replicas} -lt ${specified_replicas} || ${current_replicas} -g
   available_replicas=$(get_available_replicas)
 done
 
-echo "Deployment ${deployment} successful. All ${available_replicas} replicas are ready."
+echo "Deployment ${deployment} - ${namespace} successful. All ${available_replicas} replicas are ready."
